### ISSUE TITLE
Updates for new release?

### ISSUE THREAD

**Issue by jeremytammik** [awmcc90/NwLookup#1]
This looks like a wonderful tool! Have you updated it for NW 2021? I will do so, I guess, or try, at least. Would you like a pull request, or is the project abandoned?

**Comment by awmcc90** [comment]
Not abandoned, I've just been busy recently. I merged your PR - everything looked good and worked on my end as well. I'm going to fill in versions 2020 and 2019 as well soon.

Glad you like it!

**Comment by Coolicky** [comment]
I've just created a pull request with the 2020 & 2019 Versions. Thank You for creating the addin its been a good help. 
If You're ok I'll add Wix installer for multiple version.

**Comment by awmcc90** [comment]
I'm glad this is proving helpful to others. I checked out your PR and everything looks good/works as expected. I added one comment about changing the name of the output file for the Wix installer from RevitSetupProject to NwLookup just so the output is more clear. I'll let you update your branch instead of going through the review process. Once that's done I'll merge it.

**Comment by Coolicky** [comment]
I Didn't even realize that the name was very off :). Changed now.

**Comment by awmcc90** [comment]
Merged.
